config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :tops, only: [:show]
  resources :items
  resources :news
  resources :stores
  resources :sales do
    collection do
      get 'search'
    end
  end
  get "items_list" => "items#items_list"
  get "campaign_list" => 'tops#campaign_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "焼き菓子"},
    { id: 3, name: "生菓子"},
    { id: 4, name: "その他"}
  ]
end

app/models/holiday.rb
class Holiday <  ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "月曜日"},
    { id: 3, name: "火曜日"},
    { id: 4, name: "水曜日"},
    { id: 5, name: "木曜日"},
    { id: 6, name: "金曜日"},
    { id: 7, name: "土曜日"},
    { id: 8, name: "日曜日"},
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  # バリデーション
  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :content, length: { maximum: 1000 }
    validates :price, numericality: { greater_than_or_equal_to: 100, less_than: 5000 }
    validates :images
    validates :sale_id
    with_options numericality: { other_than: 1 } do
      validates :category_id
      validates :season_id
    end
  end

  # association
  belongs_to :user
  has_many :sales_items
  # モジュールの読み込み
  extend ActiveHash::Associations::ActiveRecordExtensions
  # activehash
  belongs_to_active_hash :category
  belongs_to_active_hash :season
  belongs_to_active_hash :sale
  # activestorage
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord

  # バリデーション
  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :content, length: { maximum: 1000 }
  end

  # アソシエーション
  belongs_to :user

  has_one_attached :image
end

app/models/sale.rb
class Sale < ActiveHash::Base
  self.data = [
    { id: 1, name: "---", sale: 100},
    { id: 2, name: "5%", sale: 0.95},
    { id: 3, name: "10%", sale: 0.9},
    { id: 4, name: "15%", sale: 0.85},
    { id: 5, name: "20%", sale: 0.8}
  ]
end

app/models/sales_item.rb
class SalesItem < ApplicationRecord

  belongs_to :item
  # belongs_to :sales_price
end

app/models/sales_price.rb
class SalesPrice < ApplicationRecord

  # has_many :sales_items
    # バリデーション
    with_options presence: true do
      validates :day, uniqueness: true
      validates :price
    end

end

app/models/salesprice_item.rb
class SalespriceItem
  include ActiveModel::Model
  attr_accessor :day, :price, :item_id, :num, :sales_price_id

  with_options presence: true do
    validates :day
    validates :price
    validates :item_id
    validates :num
    # validates :sales_price_id
  end

  def save
    sales_price = SalesPrice.create(day: day, price: price)
    SalesItem.create(item_id: item_id, num: num, sales_price_id: sales_price.id)
  end
end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "春"},
    { id: 3, name: "夏"},
    { id: 4, name: "秋"},
    { id: 5, name: "冬"}
  ]

end

app/models/store.rb
class Store < ApplicationRecord

    # バリデーション
    with_options presence: true do
      validates :name, length: {maximum: 40}
      validates :phone, format: { with: /\A\d{10}\z/ }
      validates :address, length: {maximum: 100}
      validates :open_time
      validates :close_time
      validates :images
      with_options numericality: { other_than: 1 } do
        validates :holiday_id, numericality: { less_than: 8 }
      end
    end

    # モジュールの読み込み
    extend ActiveHash::Associations::ActiveRecordExtensions
    # activehash
    belongs_to_active_hash :holiday
    # activestorage
    has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :auth_Check
  def index
    @store = Store.first
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: "正常に削除されました"
  end

  def items_list
    @items = Item.order(created_at: :DESC)
  end

  private

  # 管理者以外はルートぱすへ遷移
  def auth_Check
    if !user_signed_in?
      redirect_to root_path
    end
  end

  def item_params
    params.require(:item).permit(
      :name,
      :content,
      :price,
      :category_id,
      :season_id,
      :sale_id,
      images: []
    ).merge(user_id: current_user.id)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :auth_Check, only: [:new, :create, :edit, :upadate, :destroy]

  def index
    @newsList = News.order(created_at: :DESC)
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to items_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to items_path, notice: "正常に削除されました"
  end

  private
   # 管理者以外はルートぱすへ遷移
   def auth_Check
    if !user_signed_in?
      redirect_to root_path
    end
  end

  def news_params
    params.require(:news).permit(
      :title,
      :content,
      :image
    ).merge(user_id: current_user.id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :auth_Check

  def index
    @sales = SalesPrice.all
    @p = SalesPrice.ransack(params[:q])  # 検索オブジェクトを生成
    @results = @p.result(distinct: true).order(day: :desc).limit(30) # 検索条件にマッチした商品の情報を取得
    @date = @p.result(distinct: true).order(day: :ASC)
  end

  def new
    @items = Item.all
    @sales = SalesPrice.new
  end

  def create
    @sales = SalesPrice.new(sales_params)
    @items = Item.all
    if @sales.valid?
      @sales.save
      redirect_to sales_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
    @items = Item.all
    @sales = SalesPrice.find(params[:id])
  end

  def update
    @sales = SalesPrice.find(params[:id])
    if @sales.update(sales_params)
      redirect_to sales_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  private

  def sales_params
    params.require(:sales_price).permit(:day, :price)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @items = Item.all
    @newsList = News.order(created_at: :DESC).last(5)
  end

  def show
    @item = Item.find(params[:id])
  end

  def campaign_list
    @items = Item.where.not(sale_id: 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/_footer.html.erb
<footer class="footer">
  <div class="footer__content">
    <div class="footer__info">
      <p class="footer__info__phone">電話番号</p>
      <a href="tel:0587-54-5844" class="btn">0587-54-5844</a>
    </div>

    <div class="footer__info__privacy">
      <p>プライバシーポリシー</p>
    </div>
  </div>
</footer>
<div class="copylite">©︎ 2021 栗芳</div>

app/views/tops/_header.html.erb
<header class="header sticky-top">
  <div class="header_left">
    <a href=""></a><%= image_tag "rogo.jpg", class: "logo" %>
    <p class="logo_title"><%= link_to "栗芳", root_path, class: "logo_title" %></p>
  </div>
  <%# PC %>
  <div class="header_right">
    <nav>
      <ul class="menu-group">
        <li class="menu-item"><%= link_to "商品一覧画面", root_path %></li>
        <li class="menu-item"><%= link_to "新着情報", news_index_path %></li>
        <% if !@storeTOP.blank? %>
          <li class="menu-item"><%= link_to "店舗情報", store_path(@storeTOP.id) %></li>
        <% end %>
        <li class="menu-item"><%= link_to "キャンペーン情報", campaign_list_path %></li>
        <% if user_signed_in? %>
          <li class="menu-item"><%= link_to "管理者メニュー",  items_path, class: "menu-item" %></li>
          <li class="menu-item"><%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "menu-item" %></li>
        <% end %>
    </ul>
    </nav>
  </div>
  <%# SP %>
  <div class="nav-wrapper">
    <nav class="header-nav">
      <ul class="nav-list">
        <li class="menu-list"><%= link_to "商品一覧画面", root_path %></li>
        <li class="menu-list"><%= link_to "新着情報", news_index_path %></li>
        <% if !@storeTOP.blank? %>
          <li class="menu-list"><%= link_to "店舗情報", store_path(@storeTOP.id) %></li>
        <% end %>
        <li class="menu-list"><%= link_to "キャンペーン情報", campaign_list_path %></li>
        <% if user_signed_in? %>
          <li class="menu-list"><%= link_to "管理者メニュー",  items_path, class: "menu-list" %></li>
          <li class="menu-list"><%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "menu-list" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <%# バーガーボタン %>
  <div class="burger-btn">
    <span class="bar bar_top"></span>
    <span class="bar bar_mid"></span>
    <span class="bar bar_bottom"></span>
  </div>
</header>

app/views/tops/_itemList.html.erb
<div class="item_list row">
  <% if !@items.empty? %>
    <% @items.each do |item| %>
      <%= link_to top_path(item.id), class: "item_card col-12 col-sm-12 col-lg-6" do %>
      <% if item.sale_id != 1 %>
        <p class="campaignflg">キャンペーン中！</p>
      <% end %>
        <div class="item_image">
          <% if !item.images[1].nil? %>
            <%= image_tag item.images[1], class: "top_main_image" %>
          <% else %>
            <%= image_tag item.images[0], class: "top_main_image" %>
          <% end %>
          <%= image_tag item.images[0], class: "top_sub_image" %>
        </div>
        <div class="item_body">
          <h3 class="item_name"><%= item.name %></h3>
          <% if item.sale_id == 1 %>
            <div class="item_price">¥<%= item.price %></div>
          <% else %>
          <div class="sale">
            <div class="sale__item_price">¥<%= item.price %></div>
            <% salePrice = item.price.to_i * item.sale.sale %>
            <div class="sale__item_saleprice">=> <span> ¥<%= salePrice.to_i %></span></div>
          </div>
          <% end %>

        </div>
      <% end %>
    <% end %>
  <% else %>
    登録されている商品ありません。
  <% end %>
</div>

app/views/tops/_link.erb
<div class="item_show__btn">
  <p class="item_show__title">その他紹介</p>
  <p><%= link_to "商品一覧画面へ", root_path, class: "show_btn" %></p>
  <p><%= link_to "新着情報一覧画面へ", news_index_path, class: "show_btn" %></p>
  <p><%= link_to "キャンペーン商品画面へ", campaign_list_path, class: "show_btn" %></p>
</div>

app/views/tops/campaign_list.html.erb
<div class="campaign">
  <div class="campaign__title">
    <h3><span>キャンペーン商品情報</span></h3>
  </div>

  <div class="search">
  </div>

  <%= render 'itemList' %>
  <%= render "link" %>
</div>

app/views/tops/index.html.erb
<%# スライダー部分 %>

  <div class="slider">
    <div class="main_image1"></div>
    <div class="main_image2"></div>
    <div class="main_image3"></div>
    <div class="main_image4"></div>
    <div class="main_image5"></div>
  </div>
<%# お知らせ部分 %>
<div class="news_container">
  <div class="new_title">
    <h3><span class="new_title_font">新着情報</span></h3>
  </div>
  <div class="news_all">
    <%= link_to "新着情報一覧へ", news_index_path, class: "news_all_btn" %>
  </div>
  <% if !@newsList.empty? %>
    <%= render partial: "news/newsList", collection: @newsList %>
  <% else %>
    <div class="no_news">新着情報はまだありません。</div>
  <% end %>
</div>

<%# 商品一覧 %>
<div class="item_container">
  <div class="item_title">
    <h3><span class="item_title_font">商品一覧</span></h3>
  </div>

  <div class="search">
  </div>

  <%= render 'itemList' %>


</div>

<%# 店舗情報 %>

<div class="store_container">
  <div class="store_container__title">
    <h3><span>店舗情報</span></h3>
  </div>

<% if !@storeTOP.blank? %>
  <%= link_to store_path(@storeTOP.id) do %>
    <div class="store_container__main">
      <div class="store_container__main__left">
        <div class="store_container__main__left__image">
          <%= image_tag @storeTOP.images[0] %>
        </div>
      </div>

      <div class="store_container__main__right">
        <div class="store_container__main__right__name">
          <%= @storeTOP.name %>
        </div>

        <div class="store_container__main__right__phone">
          <span>電話番号:</span>  <%= @storeTOP.phone %>
        </div>

        <div class="store_container__main__right__address">
          住所: <%= @storeTOP.address %>
        </div>

        <div class="store_container__main__right__time">
          営業時間: <%= @storeTOP.open_time.time.strftime('%H:%M') %> ~ <%= @storeTOP.close_time.time.strftime('%H:%M') %>
        </div>

        <div class="store_container__main__right__holiday">
          定休日: <%= @storeTOP.holiday.name %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= render "link" %>
</div>

app/views/tops/show.html.erb
<div class="item_show">
  <div class="item_show__image">
  <%= image_tag @item.images[0], class: "main_image",id: "main_image_top" %>
  <ul>
    <% @item.images.each do |i| %>
      <li><%= image_tag i, class: "thumbnail_image" %></li>
    <% end %>
  </ul>
  </div>
  <div class="item_show__name">
    <p><%= @item.name %></p>
  </div>
  <div class="item_show__price">
    <% if @item.sale_id != 1 %>
      <p class="sale__item_price">¥<%= @item.price %>-</p>
      <p class="sale__item_saleprice"><span>  ¥<% saleprice = @item.price.to_i * @item.sale.sale %><%= saleprice.to_i  %>-  </span><%= @item.sale.name %>OFF</p>
    <% else %>
      <p class="normal">¥<%= @item.price %>-</p>
    <% end %>
  </div>

  <div class="item_show__content">
    <p>商品説明</p>
    <%= simple_format(@item.content) %>
  </div>
  <%= render "link" %>
</div>