config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :tops, only: [:show]
  resources :items
  resources :news
  resources :stores
  resources :sales do
    collection do
      get 'search'
    end
  end
  get "items_list" => "items#items_list"
  get "campaign_list" => 'tops#campaign_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "焼き菓子"},
    { id: 3, name: "生菓子"},
    { id: 4, name: "その他"}
  ]
end

app/models/holiday.rb
class Holiday <  ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "月曜日"},
    { id: 3, name: "火曜日"},
    { id: 4, name: "水曜日"},
    { id: 5, name: "木曜日"},
    { id: 6, name: "金曜日"},
    { id: 7, name: "土曜日"},
    { id: 8, name: "日曜日"},
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  # バリデーション
  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :content, length: { maximum: 1000 }
    validates :price, numericality: { greater_than_or_equal_to: 100, less_than: 5000 }
    validates :images
    validates :sale_id
    with_options numericality: { other_than: 1 } do
      validates :category_id
      validates :season_id
    end
  end

  # association
  belongs_to :user
  has_many :sales_items
  # モジュールの読み込み
  extend ActiveHash::Associations::ActiveRecordExtensions
  # activehash
  belongs_to_active_hash :category
  belongs_to_active_hash :season
  belongs_to_active_hash :sale
  # activestorage
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord

  # バリデーション
  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :content, length: { maximum: 1000 }
  end

  # アソシエーション
  belongs_to :user

  has_one_attached :image
end

app/models/sale.rb
class Sale < ActiveHash::Base
  self.data = [
    { id: 1, name: "---", sale: 100},
    { id: 2, name: "5%", sale: 0.95},
    { id: 3, name: "10%", sale: 0.9},
    { id: 4, name: "15%", sale: 0.85},
    { id: 5, name: "20%", sale: 0.8}
  ]
end

app/models/sales_item.rb
class SalesItem < ApplicationRecord

  belongs_to :item
  # belongs_to :sales_price
end

app/models/sales_price.rb
class SalesPrice < ApplicationRecord

  # has_many :sales_items
    # バリデーション
    with_options presence: true do
      validates :day, uniqueness: true
      validates :price
    end

end

app/models/salesprice_item.rb
class SalespriceItem
  include ActiveModel::Model
  attr_accessor :day, :price, :item_id, :num, :sales_price_id

  with_options presence: true do
    validates :day
    validates :price
    validates :item_id
    validates :num
    # validates :sales_price_id
  end

  def save
    sales_price = SalesPrice.create(day: day, price: price)
    SalesItem.create(item_id: item_id, num: num, sales_price_id: sales_price.id)
  end
end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "春"},
    { id: 3, name: "夏"},
    { id: 4, name: "秋"},
    { id: 5, name: "冬"}
  ]

end

app/models/store.rb
class Store < ApplicationRecord

    # バリデーション
    with_options presence: true do
      validates :name, length: {maximum: 40}
      validates :phone, format: { with: /\A\d{10}\z/ }
      validates :address, length: {maximum: 100}
      validates :open_time
      validates :close_time
      validates :images
      with_options numericality: { other_than: 1 } do
        validates :holiday_id, numericality: { less_than: 8 }
      end
    end

    # モジュールの読み込み
    extend ActiveHash::Associations::ActiveRecordExtensions
    # activehash
    belongs_to_active_hash :holiday
    # activestorage
    has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :auth_Check
  def index
    @store = Store.first
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: "正常に削除されました"
  end

  def items_list
    @items = Item.order(created_at: :DESC)
  end

  private

  # 管理者以外はルートぱすへ遷移
  def auth_Check
    if !user_signed_in?
      redirect_to root_path
    end
  end

  def item_params
    params.require(:item).permit(
      :name,
      :content,
      :price,
      :category_id,
      :season_id,
      :sale_id,
      images: []
    ).merge(user_id: current_user.id)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :auth_Check, only: [:new, :create, :edit, :upadate, :destroy]

  def index
    @newsList = News.order(created_at: :DESC)
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to items_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to items_path, notice: "正常に削除されました"
  end

  private
   # 管理者以外はルートぱすへ遷移
   def auth_Check
    if !user_signed_in?
      redirect_to root_path
    end
  end

  def news_params
    params.require(:news).permit(
      :title,
      :content,
      :image
    ).merge(user_id: current_user.id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :auth_Check

  def index
    @sales = SalesPrice.all
    @p = SalesPrice.ransack(params[:q])  # 検索オブジェクトを生成
    @results = @p.result(distinct: true).order(day: :desc).limit(30) # 検索条件にマッチした商品の情報を取得
    @date = @p.result(distinct: true).order(day: :ASC)
  end

  def new
    @items = Item.all
    @sales = SalesPrice.new
  end

  def create
    @sales = SalesPrice.new(sales_params)
    @items = Item.all
    if @sales.valid?
      @sales.save
      redirect_to sales_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
    @items = Item.all
    @sales = SalesPrice.find(params[:id])
  end

  def update
    @sales = SalesPrice.find(params[:id])
    if @sales.update(sales_params)
      redirect_to sales_path, notice: "編集に成功しました"
    else
      render :edit
    end
  end

  private

  def sales_params
    params.require(:sales_price).permit(:day, :price)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :auth_Check, only: [:new, :create, :edit, :upadate, :destroy]

  def index
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @store = Store.find(@storeTOP.id)
    if @store.update(store_params)
      redirect_to items_path, notice: "登録に成功しました"
    else
      render :new
    end
  end

  def show
  end

  private
  def store_params

  end
  # 管理者以外はルートぱすへ遷移
  def auth_Check
    if !user_signed_in?
      redirect_to root_path
    end
  end

  def store_params
    params.require(:store).permit(
      :name,
      :phone,
      :address,
      :open_time,
      :close_time,
      :holiday_id,
      images: []
    )
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @items = Item.all
    @newsList = News.order(created_at: :DESC).last(5)
  end

  def show
    @item = Item.find(params[:id])
  end

  def campaign_list
    @items = Item.where.not(sale_id: 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/items/_errors.html.erb
<% if model.errors.any? %>
<ul>
<% model.errors.full_messages.each do |m| %>
  <li><%= m %></li>
<% end %>
</ul>
<% end %>

app/views/items/_itemform.html.erb
<div class="items">
  <div class="item_name">
    <label for="">商品名</label>
    <%= f.text_field :name, class: "name", id: "name", placeholder: "商品名を入力" %>
  </div>
  <div class="item_content">
    <label for="">商品説明</label>
    <%= f.text_area :content, class: "content", id: "content", placeholder: "商品説明文を入力" %>
    <p class="conent_count">
      <span class="content_count">0</span>/1000
    </p>
  </div>
  <div class="item_price">
    <label for="">商品価格</label>
    <%= f.text_field :price, class: "price", id: "price", placeholder: "商品価格を入力" %>
  </div>
  <div class="item_category">
    <label for="">商品カテゴリー</label>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>
  <div class="item_season">
    <label for="">季節</label>
    <%= f.collection_select(:season_id, Season.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>
  <div class="item_sale">
    <label for="">キャンペーン価格</label>
    <%= f.collection_select(:sale_id, Sale.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>
  <%# TODO リファクタリング必要 %>
  <div class="item_image__input">

    <div class="item_image__filed">
      <label for="">商品画像(メイン画像)<span>必須</span></label>
      <%= f.file_field :image, id: "item-image1", class:"file" ,name: "item[images][]" %>
    </div>

    <div class="item_image__filed">
      <label for="">商品画像(切り替わり画像)<span>必須</span></label>
      <%= f.file_field :image, id: "item-image2", class:"file" ,name: "item[images][]" %>
    </div>

    <div class="item_image__filed">
      <label for="">商品画像<span>任意</span></label>
      <%= f.file_field :image, id: "item-image3", class:"file" ,name: "item[images][]" %>
    </div>

    <div class="item_image__filed">
      <label for="">商品画像<span>任意</span></label>
      <%= f.file_field :image, id: "item-image4", class:"file" ,name: "item[images][]" %>
    </div>

    <div class="item_image__filed">
      <label for="">商品画像<span>任意</span></label>
      <%= f.file_field :image, id: "item-image5", class:"file" ,name: "item[images][]" %>
    </div>


    <%# 編集時編集前の画像表示 TODO 各登録・編集機能に実装、テンプレートとして切り出す  %>
  <% if @item.images.attached? %>
    <p>編集前画像</p>
    <% @item.images.each do |image| %>
    <%= image_tag image ,class: "edit_image_size" %></p>
    <% end %>
  <% end %>
  <%# -------------------------------------------------------------------- %>
  </div>
</div>
<div class="item_btn">
  <%= f.submit "登録する", class: "item_btn__submit" %>
  <%= link_to "戻る", items_path, class: "item_btn__back" %>
</div>

app/views/items/_items.html.erb
<tbody>
  <tr>
    <td><%= items.name %></td>
    <td><%= items.price %></td>
    <td><%= items.category.name %></td>
    <td><%= items.season.name %></td>
    <td><%= items.sale.name %></td>
    <td><%= image_tag items.images[0] %></td>
    <td><%= link_to "詳細", top_path(items.id) %></td>
    <td><%= link_to "編集", edit_item_path(items.id) %></td>
    <td><%= link_to "削除", item_path(items.id), method: :delete, data: { confirm:"削除する場合データを戻せません、本当に削除しますか？" } %></td>
  </tr>
</tbody>

app/views/items/edit.html.erb
<div class="new_item">
  <div class="new_item__title">
    <h3>編集画面</h3>
  </div>
  <div class="new_item__form">
    <%= form_with model: @item, local:true do |f| %>
      <%# エラーメッセージ %>
      <%= render "errors", model: f.object %>
      <%# form %>
      <%= render 'itemform', { f: f } %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="kanri_title">
  <h3>管理者メニュー</h3>
</div>

<div class="menu">
  <%= link_to "商品登録", new_item_path, class: "kanri_list item_input" %>
  <%= link_to "商品編集・削除", items_list_path, class: "kanri_list item_edit" %>
  <%= link_to "新着情報登録", new_news_path, class: "kanri_list news_input" %>
  <%= link_to "新着情報編集・削除", news_index_path, class: "kanri_list news_edit" %>
  <%# 最初の登録以外は編集になる %>
  <% if @store.blank? %>
    <%= link_to "店舗情報登録", new_store_path, class: "kanri_list store_input" %>
  <% else %>
    <%= link_to "店舗情報編集", edit_store_path(@store.id), class: "kanri_list store_edit" %>
  <% end %>
  <%= link_to "売上登録", new_sale_path, class: "kanri_list news_edit" %>
  <%= link_to "売上情報確認・編集", sales_path, class: "kanri_list news_edit" %>
</div>

app/views/items/items_list.html.erb
<div class="item_list">
  <% if !@items.empty? %>
    <table class="table" border="1">
      <thead>
        <tr>
          <th>商品名</th>
          <th>商品価格</th>
          <th>カテゴリー</th>
          <th>季節</th>
          <th>キャンペーン</th>
          <th>メイン画像</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <%= render partial: "items", collection: @items %>
    </table>
  <% else %>
  <div class="no_items">
    <h3>商品を登録してください。</h3>
  </div>
  <% end %>
  <%= link_to "戻る", items_path, class: "news_form__btn__back" %>
</div>

app/views/items/new.html.erb
<div class="new_item">
  <div class="new_item__title">
    <h3>商品登録画面</h3>
  </div>
  <div class="new_item__form">
    <%= form_with model: @item, local:true do |f| %>
      <%# エラーメッセージ %>
      <%= render "errors", model: f.object %>

      <div class="items">
        <div class="item_name">
          <label for="">商品名</label>
          <%= f.text_field :name, class: "name", id: "name", placeholder: "商品名を入力" %>
        </div>
        <div class="item_content">
          <label for="">商品説明</label>
          <%= f.text_area :content, class: "content", id: "content", placeholder: "商品説明文を入力" %>
        </div>
        <div class="item_price">
          <label for="">商品価格</label>
          <%= f.text_field :price, class: "price", id: "price", placeholder: "商品価格を入力" %>
        </div>
        <div class="item_category">
          <label for="">商品カテゴリー</label>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="item_season">
          <label for="">季節</label>
          <%= f.collection_select(:season_id, Season.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="item_sale">
          <label for="">キャンペーン価格</label>
          <%= f.collection_select(:sale_id, Sale.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
        <div class="item_image">
          <label for="">商品画像(正面画像)</label>
          <%= f.file_field :image, id: "item-image", class:"file" %>
          <div class="preview"></div>
        </div>
      </div>
      <div class="item_btn">
        <%= f.submit "登録する", class: "item_btn__submit" %>
        <%= link_to "戻る", items_path, class: "item_btn__back" %>
      </div>
    <% end %>
  </div>
</div>

app/views/news/_newsList.html.erb
<div class="news_index__menu">
  <%= link_to news_path(newsList.id), class: "news_index__lists" do %>
      <div class="news_index__list__time"><%= newsList.created_at.strftime('%Y/%m/%d') %></div>
      <div class="news_index__list__title"><%= newsList.title %></div>
  <% end %>
  <% if user_signed_in? %>
      <div class="news_index__list__edit"><%= link_to "編集", edit_news_path(newsList.id) %></div>
      <div class="news_index__list__delete"><%= link_to "削除", news_path(newsList.id), method: :delete, data: { confirm:"削除する場合データを戻せません、本当に削除しますか？" } %></div>
  <% end %>
  </div>

app/views/news/_newsform.html.erb
<div class="news_form">
  <div class="news_form__title">
    新着情報タイトル <span class="required">必須</span>
  </div>
  <%= f.text_field :title, class: "news_form__title__area", placeholder: "タイトル（40文字まで）", maxlength: "40" %>

  <div class="news_form__content">
    新着情報詳細 <span class="required">必須</span>
  </div>
  <%= f.text_area :content, id: "content", rows: 10, class: "news_form__content__area", placeholder: "詳細情報（1000文字まで）", maxlength: "1000" %>
  <p class="conent_count">
      <span class="content_count">0</span>/1000
    </p>

  <div class="news_form__image">
    画像情報
  </div>

  <%# 編集時編集前の画像表示 %>
  <% if @news.image.attached? %>
    <p>編集前画像
    <%= image_tag @news.image ,class: "edit_image_size" %></p>
  <% end %>

  <%= f.file_field :image, class: [:news_form__image__area] %>
  <div class="" id="preview"></div>

  <div class="news_form__btn">
    <%= f.submit "作成！", class: "news_form__btn__submit" %>
    <%= link_to "戻る", items_path, class: "news_form__btn__back" %>
  </div>

 </div>

app/views/news/edit.html.erb
<div class="news_new__container">

  <div class="news_header">
    <div class="news_header__title">
      <h3><span>新着情報編集</span></h3>
    </div>
  </div>

  <div class="news_main">
    <%= form_with model: @news, local: true do |f| %>
      <%# エラーメッセージ %>
      <%= render 'items/errors', model: f.object %>

      <%# 登録フォーム %>
      <%= render 'newsform', { f: f } %>
    <% end %>
  </div>

</div>

app/views/news/index.html.erb
<div class="news_index">

  <div class="news_index__title">
    <h3><span>新着情報一覧画面</span></h3>
  </div>


<% if !@newsList.empty? %>
    <%= render partial: "newsList", collection: @newsList %>
<% else %>
  <div class="no_news">新着情報はまだありません。</div>
<% end %>

</div>

app/views/news/new.html.erb
<div class="news_new__container">

  <div class="news_header">
    <div class="news_header__title">
      <h3><span>新着情報一覧</span></h3>
    </div>
  </div>

  <div class="news_main">
    <%= form_with model: @news, local: true do |f| %>
      <%# エラーメッセージ %>
      <%= render 'items/errors', model: f.object %>

      <%# 登録フォーム %>
      <%= render 'newsform', { f: f } %>
    <% end %>
  </div>

</div>

app/views/news/show.html.erb
<div class="news_show">

  <div class="news_show__title">
    <h3> <span>新着情報</span> </h3>
  </div>

  <div class="news_show__main">
    <div class="news_show__news_title">
      タイトル：<%= @news.title %>
    </div>


    <div class="news_show__content">
      <p>詳細：</p>
      <%= simple_format(@news.content) %>

    </div>

    <% if @news.image.attached? %>
      <div class="news_show__image">
        <p>キャンペーンimage</p>
        <%= image_tag @news.image %>
      </div>
    <% end %>
  </div>

  <%= render "tops/link" %>
</div>

app/views/sales/_sales_form.html.erb
<h1>商品一覧</h1>

    <% i = 0%>
    <% @items.each do |item| %>
      <div class="sales__item">
        <p class="sales__item__name"><%= item.name %></p>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.number_field :num ,class: "num[#{i}] num" %>
        <span> × </span>
        <% if item.sale_id == 1 %>
          <span class="sales_price"><%= item.price  %></span>
        <% else %>
          <span class="sales_price"><% saleprice = item.price.to_i * item.sale.sale %><%= saleprice.to_i  %></span>
        <% end %>

      <% i += 1 %>
      </div>
    <% end %>
  </div>

app/views/sales/edit.html.erb
<div class="sales">
  <%= form_with model: @sales, method: :PUT, url: sale_path(@sales.id),class: "sales__form", local: true do |f| %>
  <div class="sales__input">
  <%# エラーメッセージ %>
  <%= render "items/errors", model: f.object %>
    <div class="sales__day">
    </div>

    <%# 商品一覧 %>
    <%= render "sales_form", { f: f } %>

  <div class="sales__suminput">
    <div class="sales__sum">
      <h1>売り上げ合計</h1>
      <%= f.text_field :price, value: "0" %>
    </div>
    <div class="sales__submit">
      <%= f.submit "売り上げを登録する" %>
    </div>
    <% end %>
  </div>
  <%= link_to "戻る", items_path, class: "news_form__btn__back" %>
</div>

app/views/sales/index.html.erb
<div class="sales">

  <div class="sales__index__title">
    <h3><span>検索画面</span></h3>
  </div>

  <div class="sales__index__body">
      <%= search_form_for @p, url: sales_path do |f| %>
        <p><%= f.label "範囲検索(最大30件までしか表示されません)", class: "sales__index__body__title" %></p>

        <div class="sales__index__body__input">
          <p><%= f.date_field :day_gteq %> 〜</p>
          <p><%= f.date_field :day_lteq%></p>
        </div>

        <%= f.submit '検索', class: "btn btn-primary" %>
        <%= link_to '戻る', items_path, class: "btn" %>
      <% end %>

    <div class="sales__index__results">
      <p>30件までの情報を表示します</p>
      <% if @results.length !=0 %>
        <% sum = 0 %>
        <% @results.each do |result| %>
        <p class="row">
            <span class="col-3">[<%= result.day %>]</span>
            <span class="col-3">売上金額: ¥<%= result.price %>-</span>
            <span class="col-2"><%= link_to "編集", edit_sale_path(result.id) %></span>
            <% sum += result.price %>
        </p>
        <% end %>
      <% else %>
        該当するデータはありません
      <% end %>
      <% if sum != 0 %>
        <p>合計:<%= sum %></p>
      <% end %>

    </div>
  </div>
  <p id="notice"></p>


<%# チャート表示 %>
<%= column_chart @date.group(:day).sum(:price), id: "column-chart", width: "800px", height: "500px" %>

</div>

app/views/sales/new.html.erb
<div class="sales">
  <%= form_with model: @sales, url: sales_path,class: "sales__form", local: true do |f| %>
  <div class="sales__input">
  <%# エラーメッセージ %>
    <%= render "items/errors", model: f.object %>

    <div class="sales__day">
      <h1>日付</h1>
      <%= f.date_field :day, class: "sales__day__input" %>
    </div>

  <%# 商品一覧 %>
  <%= render "sales_form", { f: f } %>

  <div class="sales__suminput">
    <div class="sales__sum">
      <h1>売り上げ合計</h1>
      <%= f.text_field :price, value: "0" %>
    </div>
    <div class="sales__submit">
      <%= f.submit "売り上げを登録する" %>
    </div>
    <% end %>
  </div>
  <%= link_to "戻る", items_path, class: "news_form__btn__back" %>
</div>

app/views/sales/sales_list.html.erb
<div class="sales_edit">
<div class="sales_edit__title">
  <h3><span>売上情報確認</span></h3>
</div>

<div class="sales_edit__search">
  <p class="sales_edit__search__year">
    </p>
  <p class="sales_edit__search__mons"></p>
</div>

</div>

app/views/stores/_storeform.html.erb
<div class="store_form">

  <div class="store_form__name">
    店舗名
  </div>
  <%= f.text_field :name, class:"store_form__name__area", maxlength: "40" %>

  <div class="store_form__phone">
    電話番号
  </div>
  <%= f.text_field :phone, class: "store_form__phone__area", maxlength: "10", placeholder: "ハイフンなしで記載してください" %>

  <div class="store_form__address">
    住所
  </div>
  <%= f.text_field :address, class: "store_form__address__area", maxlength: "100" %>

  <div class="store_form__opentime">
    開店時間
  </div>
  <%# TODO リファクタリングする %>
  <%= f.time_select :open_time, class: "store_form__opne__time" %>


    <div class="store_form__close_time">
      閉店時間
    </div>
    <%= f.time_select :close_time, class: "store_form__close__time" %>

    <div class="store_form__holiday">
      定休日
    </div>
    <%= f.collection_select(:holiday_id, Holiday.all, :id, :name, {}, {class:"select-box"}) %>

    <div class="store_form__images">
      店舗外観
      <%= f.file_field :image, class:"file" ,name: "store[images][]" %>
    </div>

    <div class="store_form__images">
      店舗内観
      <%= f.file_field :image, class:"file" ,name: "store[images][]" %>
    </div>

    <div class="item_btn">
      <%= f.submit "登録する", class: "item_btn__submit" %>
      <%= link_to "戻る", items_path, class: "item_btn__back" %>
    </div>
</div>

app/views/stores/edit.html.erb
<div class="news_new__container">

  <div class="news_header">
    <div class="news_header__title">
      <h3><span>店舗編集</span></h3>
    </div>
  </div>

  <div class="news_main">
    <%= form_with model: @storeTOP, local: true do |f| %>
      <%# エラーメッセージ %>
      <%= render 'items/errors', model: f.object %>

      <%# 登録フォーム %>
      <%= render 'storeform', { f: f } %>
    <% end %>
  </div>

</div>

app/views/stores/new.html.erb
<div class="news_new__container">

  <div class="news_header">
    <div class="news_header__title">
      <h3><span>店舗登録</span></h3>
    </div>
  </div>

  <div class="news_main">
    <%= form_with model: @store, local: true do |f| %>
      <%# エラーメッセージ %>
      <%= render 'items/errors', model: f.object %>

      <%# 登録フォーム %>
      <%= render 'storeform', { f: f } %>
    <% end %>
  </div>

</div>

app/views/stores/show.html.erb
<div class="store_show">

  <div class="store_show__title">
    <h3><span>店舗詳細</span></h3>
  </div>

  <div class="store_show__main">

    <div class="show__main__lift">
      <%= image_tag @storeTOP.images[0], class: "show__main__lift__image",id: "main_image_top" %>
      <ul>
        <% @storeTOP.images.each do |i| %>
          <li><%= image_tag i, class: "thumbnail_image" %></li>
        <% end %>
      </ul>
    </div>


    <div class="show__main__right">

      <div class="show__main__right__name">
      店名<br>
        <%= @storeTOP.name %>
      </div>
      <div class="show__main__right__phone">
      電話番号<br>
        <%= @storeTOP.phone %>
      </div>
      <div class="show__main__right__address">
        住所<br>
        <%= @storeTOP.address %>
      </div>
      <div class="show__main__right__time">
        営業時間: <%= @storeTOP.open_time.time.strftime('%H:%M') %> ~ <%= @storeTOP.close_time.time.strftime('%H:%M') %>
      </div>
      <div class="show__main__right__holiday">
        定休日: <%= @storeTOP.holiday.name %>
      </div>
    </div>

  </div>
  <%# GooglemapAPI導入予定 %>
  <p>Googleマップ</p>
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4727.195138729142!2d136.88872574390257!3d35.345673655136636!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60030be20f1f1a35%3A0xd1bcef5b92747e43!2z5qCX6Iqz!5e0!3m2!1sja!2sjp!4v1616836388504!5m2!1sja!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
  <%= render "tops/link" %>
</div>